### ISSUE TITLE
easy-to-fix bug in 'mask_and_norm_backward_actions' function

### ISSUE THREAD

**Issue by kzk2000** [mbi2gs/gflownet_tf2#1]
Digging through your (awesome) code, I believe I discovered a bug in your backwards masking, the mask defined in line 176 is not applied in line 177 (in fact it's not used at all)

https://github.com/mbi2gs/gflownet_tf2/blob/aece0a5463dc0df4d1773bebdb136efbb35fe317/gfn.py#L176

hope this helps

**Comment by mbi2gs** [comment]
Good catch! I just pushed the update.
